Pbi-200-218 : filter email status by email
kg-procurement/kg-procurement-ui pull request #62
Opened 2024-11-29 04:12 UTC by bryannaufal

## Describe your changes
- Adding Page Header for email status page
- Put filter by email input and integrate

## Issue ticket number and link
https://linear.app/adudu/issue/ADU-218/integrate-filter-emailed-vendors
https://linear.app/adudu/issue/ADU-200/frontend-filter-emailed-vendors

![image](https://github.com/user-attachments/assets/0c7f7290-5a81-4e7d-a303-a95ee5491da7)

2024-11-29 15:08 UTC, edutjie commented
There is one minor issue from sonarcloud, "Remove this unused import of 'PaginationArgs'." Please solve it 🙏. The rest is good.

2024-12-01 05:13 UTC, FreeJ1nG requested changes

2024-12-01 05:13 UTC, FreeJ1nG commented on src/routes/__tests__/email.test.tsx
> +    expect(screen.getByText('Lorem Ipsum')).toBeInTheDocument()
Can you please remove this "Lorem Ipsum" part? it's no longer needed

2024-12-01 05:13 UTC, FreeJ1nG commented on src/routes/email.tsx
> +        </Typography>
Here too

2024-12-01 06:15 UTC, FreeJ1nG commented
LGTM

2024-12-01 06:15 UTC, merged